### PR TITLE
refactor: dark theme system

### LINKED ISSUE #55: Refactoring of the theme toggle
### The dark theme system code is not well written.

- It's directly changing the colors of the presented elements in the DOM using JavaScript by selecting each element using querySelector on the theme toggle.
- The theme color is not persistent

### My approach would be

- We will just toggle one class of body element.
- CSS will handle the text and background color of DOM elements.

### I would like to work on this.

### PR DESCRIPTION
**Pull request by g1mishra**
Closes #55

### CODE REVIEW

**Comment by g1mishra** [comment]
Bro already added, can you please add 5-10 todo item and check

**Comment by Soumyajit2825** [comment]
It's nice to work with you
Thanks for this great contribution dude!!!!

**Comment by g1mishra** [comment]
No problem brother ☺️.

**Comment by Soumyajit2825** [comment]
If you need more contribution for Hacktoberfest you can contribute in my other repo also
[MESSI_MANIA a simple website for LM10 lovers](https://github.com/Soumyajit2825/MESSI_MANIA)

**Pull request merged**
