### PR TITLE
midified the apperance of project by changing in html and css file

### PR DESCRIPTION
**Pull request by Urmilasc**

### CODE REVIEW

**Comment by Urmilasc** [comment]
Hello sir , I sended the pull request , please review it

**Comment by Soumyajit2825** [comment]
@Urmilasc THIS branch has some merge conflicts issues. Remove that you can search it via Youtube that what is a merge conflict

**Comment by Urmilasc** [comment]
Hello , I resolved that merge conflicts , it is right , please let me know

**Comment by Soumyajit2825** [comment]
Yes. DONE

**Comment by Urmilasc** [comment]
Thanks you so much for your guidance

**Comment by Soumyajit2825** [comment]
My pleasure

**Pull request merged**
