### PR TITLE
Changed Layout, Added Deadline Feature

### PR DESCRIPTION
**Pull request by eccentriccoder01**
Changed the design and separated the two boxes... And added the Date Deadline feature

### CODE REVIEW

**Comment by Soumyajit2825** [comment]
image
Can you check this one??
The dark-light button is colliding with the margin!

**Review by Soumyajit2825 — CHANGES_REQUESTED** [review]
@eccentriccoder01 Just check that one thing rest are awesome!

**Comment by eccentriccoder01** [comment]
> @eccentriccoder01 Just check that one thing rest are awesome!

Owkkay thanks...I'm closing this and creating another pull request then...

**Review by Soumyajit2825 — APPROVED** [review]
perfect

**Pull request merged**
