### PR TITLE
#77 Solved: Added Logo, Filter & Reset Functionality

### PR DESCRIPTION
**Pull request by Soumya-2003**
**Issue #77 Solved**
I've added the Logo in the top left corner, Along with the Filter options and Reset Functionality.
**Approach for Filtering:** _Three filter options are available - All, Pending & Completed. While clicking on Pending option, the completed-tasks-container becomes inactive and only incomplete-tasks-container becomes active and displayed. Same happens in case of clicking Completed option, it actives only the completed-tasks-container and inactive the incomplete-tasks-container.
But while clicking on "All" under filter options, both the container becomes active and displayed._
**Approach for Reset Button:** _While clicking on reset button, all the tasks added by the user is cleared by clearing the tasks array and then rendered._

Filter, reset

### CODE REVIEW

**Comment by Soumyajit2825** [comment]
image
Can you fix two things?

1. Allignment of the theme toggle button
2. The bottom of the box is not visible while selected the all from the filters

**Comment by Soumyajit2825** [comment]
image

Try to maintain this design @Soumya-2003

**Comment by Soumyajit2825** [comment]
@Soumya-2003 please do pull the recent changes to resolve the conflicts. I have merged two new PRs

**Comment by eccentriccoder01** [comment]
@Soumya-2003 Can you jus' do one thing❔Use the same logo which you created to create a set of favicons(you may use an online favicon generator) for all types of screens, and place the favicon's directory in the index.html... That'll solve the complete issue of Logos...

**Review by eccentriccoder01 — COMMENTED** [review]
The Logo's perfect...Jus' do the favicon thing as I said, and make the other necessary changes instructed by Soumyajit...

**Comment by Soumya-2003** [comment]
> > @Soumya-2003 Can you jus' do one thing❔Use the same logo which you created to create a set of favicons(you may use an online favicon generator) for all types of screens, and place the favicon's directory in the index.html... That'll solve the complete issue of Logos...
> 
> better @Soumya-2003 do this

Are you saying to use the same favicon image as the Logo image?

**Comment by Soumyajit2825** [comment]
> > > @Soumya-2003 Can you jus' do one thing❔Use the same logo which you created to create a set of favicons(you may use an online favicon generator) for all types of screens, and place the favicon's directory in the index.html... That'll solve the complete issue of Logos...
> > 
> > 
> > better @Soumya-2003 do this
> 
> Are you saying to use the same favicon image as the Logo image?

Yes!

**Comment by eccentriccoder01** [comment]
> > > @Soumya-2003 Can you jus' do one thing❔Use the same logo which you created to create a set of favicons(you may use an online favicon generator) for all types of screens, and place the favicon's directory in the index.html... That'll solve the complete issue of Logos...
> > 
> > 
> > better @Soumya-2003 do this
> 
> Are you saying to use the same favicon image as the Logo image?

Logo image as the favicon image I mean...

**Comment by Soumyajit2825** [comment]
Any update @Soumya-2003 ?

**Comment by Soumya-2003** [comment]
> Any update @Soumya-2003 ?



> Any update @Soumya-2003 ?

I've done what you have told and my last commit message was "Properly set the logo" done yesterday. Please check whether everything is alright or not otherwise I will fork your repo once more and again follow the whole contribution procedure by tonight.

**Comment by Soumyajit2825** [comment]
> > Any update @Soumya-2003 ?
> 
> > Any update @Soumya-2003 ?
> 
> I've done what you have told and my last commit message was "Properly set the logo" done yesterday. Please check whether everything is alright or not otherwise I will fork your repo once more and again follow the whole contribution procedure by tonight.

yeah all done, just now pull the changes and push your filter & reset functions,dont change any designs

**Pull request closed without merging**
