### PR TITLE
Reversed the order in which list items are displayed

### PR DESCRIPTION
**Pull request by sayanbose-0000**
In to do lists, it is expected that the most recently added element appears at the top and the oldest appear at the bottom. However, the current code did the opposite. I fixed it to resolve the issue. It is a simple fix, with the loop changed a bit

### CODE REVIEW

**Comment by Soumyajit2825** [comment]
Will be checked within tonight @sayanbose-0000! 
Please mention the issue number while doing the PR...

**Comment by sayanbose-0000** [comment]
Issue no. #75

**Review by Soumyajit2825 — APPROVED** [review]
Nice work

**Comment by sayanbose-0000** [comment]
added the necessary changes with respect to issue #80

**Pull request merged**
