### PR TITLE
Add reward features upon completion of work

### PR DESCRIPTION
**Pull request by rko0211**
Kindly review my work..

Resolve issue :  #91

### CODE REVIEW

**Comment by rko0211** [comment]
Hey can you tell me why labels changed from Hard to Medium labels

**Comment by Soumyajit2825** [comment]
@rko0211 There was three jobs in that issue

1- Adding reward on completing tasks
2- Opening new features on completing tasks
3- Congratulating of completing tasks.

You have done only once that's why I have changed the labels!

**Comment by rko0211** [comment]
Ok , thank you

**Comment by Soumyajit2825** [comment]
Always welcome!!!
Thanks for contributing

**Pull request merged**
